spring.application.name=product
spring.datasource.url=jdbc:postgresql://localhost:5432/order_management
spring.datasource.username = postgres
spring.datasource.password = Papaji@9611
spring.jpa.hibernate.ddl-auto=update
